
name: Android-Чтосмотреть-宝箱
on:
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqboxbody: ${{ secrets.ZQBOXBODY }}
        zqboxbody2: ${{ secrets.ZQBOXBODY2 }}
        zqboxbody3: ${{ secrets.ZQBOXBODY3 }}
        zqboxbody4: ${{ secrets.ZQBOXBODY4 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Xəzinəsandığı】'
        if: env.zqboxbody
        run: |
          node Android-Чтосмотреть-Xəzinəsandığı.js
        env:
          zqboxbody: ${{ secrets.ZQBOXBODY }}
          

      - name: '运行 【Android-Чтосмотреть-birbaxın二】'
        if: env.YOUTH_READ2
        run: |
          node Android-Чтосмотреть-Xəzinəsandığı.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY2 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE }}

      
