name: Android-Чтосмотреть-阅读文章
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5,13 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqwzbody: ${{ secrets.ZQWZBODY }}
        zqwzbody2: ${{ secrets.ZQWZBODY2 }}
        zqwzbody3: ${{ secrets.ZQWZBODY3 }}
        zqwzbody4: ${{ secrets.ZQWZBODY4 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-oxumaq2】'
        if: env.zqwzbody
        run: |
          node Android-Чтосмотреть-oxumaq2.js
        env:
          zqwzbody: ${{ secrets.ZQWZBODY }} ${{ secrets.ZQWZBODY1 }}
          zq_timebody: ${{ secrets.ZQ_TIMEBODY }}

      - name: '运行 【Android-Чтосмотреть-oxumaq2二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          zqwzbody: ${{ secrets.ZQWZBODY2 }}
          zq_timebody: ${{ secrets.ZQ_TIMEBODY5 }}

